##
# Generated by Gemini from old SQL migration file for convenience reasons.
# Code generation was supervised and manually checked.

from datetime import datetime
from typing import Optional

from pydantic import BaseModel
from sqlalchemy import Index, text
from sqlmodel import Field, Relationship, SQLModel


class User(SQLModel, table=True):
    __tablename__ = "users"  # type: ignore

    id: str = Field(primary_key=True)
    username: str = Field(unique=True)
    display_name: str
    password_hash: str
    bio: Optional[str] = None
    avatar_url: Optional[str] = None
    created_at: Optional[datetime] = Field(
        default=None, sa_column_kwargs={"server_default": text("CURRENT_TIMESTAMP")}
    )


class Server(SQLModel, table=True):
    __tablename__ = "servers"  # type: ignore

    id: str = Field(primary_key=True)
    name: str
    owner_id: str = Field(foreign_key="users.id")
    icon_url: Optional[str] = None
    created_at: Optional[datetime] = Field(
        default=None, sa_column_kwargs={"server_default": text("CURRENT_TIMESTAMP")}
    )


class ServerWithMembership(BaseModel):
    id: str
    name: str
    icon_url: Optional[str]
    role: str
    joined_at: datetime


class ServerMember(SQLModel, table=True):
    __tablename__ = "server_members"  # type: ignore

    server_id: str = Field(foreign_key="servers.id", primary_key=True)
    user_id: str = Field(foreign_key="users.id", primary_key=True, index=True)
    role: str = Field(default="member")
    joined_at: Optional[datetime] = Field(
        default=None, sa_column_kwargs={"server_default": text("CURRENT_TIMESTAMP")}
    )


class Channel(SQLModel, table=True):
    __tablename__ = "channels"  # type: ignore

    id: str = Field(primary_key=True)
    server_id: str = Field(foreign_key="servers.id")
    name: str
    created_at: Optional[datetime] = Field(
        default=None, sa_column_kwargs={"server_default": text("CURRENT_TIMESTAMP")}
    )


class Message(SQLModel, table=True):
    __tablename__ = "messages"  # type: ignore

    id: Optional[int] = Field(default=None, primary_key=True)
    channel_id: str = Field(foreign_key="channels.id", index=True)
    sender_id: Optional[str] = Field(default=None, foreign_key="users.id")
    content: Optional[str] = None
    message_type: str = Field(default="text")
    edited_at: Optional[datetime] = None
    reply_to_id: Optional[int] = Field(default=None, foreign_key="messages.id")
    is_deleted: int = Field(default=0)
    created_at: Optional[datetime] = Field(
        default=None, sa_column_kwargs={"server_default": text("CURRENT_TIMESTAMP")}
    )

    attachments: list[Attachment] = Relationship(back_populates="message")
    replied_message: Optional["Message"] = Relationship(
        sa_relationship_kwargs={"remote_side": "Message.id"}
    )
    __table_args__ = (Index("idx_messages_created_at", "channel_id", "created_at"),)


class AttachmentResponse(BaseModel):
    id: str
    url: str
    file_type: str
    file_size: int
    file_name: str
    created_at: datetime


class RepliedMessagePreview(BaseModel):
    id: int
    content: Optional[str]
    sender_username: str


class ChatMessageResponse(BaseModel):
    id: int
    channel_id: str
    sender_id: str
    sender_username: str
    sender_display_name: str
    sender_avatar_url: Optional[str]
    content: Optional[str]
    message_type: str
    edited_at: Optional[datetime]
    reply_to_id: Optional[int]
    is_deleted: bool
    created_at: datetime
    attachments: list[AttachmentResponse] = []
    replied_message: Optional[RepliedMessagePreview] = None


class Attachment(SQLModel, table=True):
    __tablename__ = "attachments"  # type: ignore

    id: str = Field(primary_key=True)
    message_id: Optional[int] = Field(foreign_key="messages.id", default=None)
    uploader_id: str = Field(foreign_key="users.id")
    url: str
    file_type: str
    file_size: int
    file_name: str
    created_at: datetime = Field(
        default=None, sa_column_kwargs={"server_default": text("CURRENT_TIMESTAMP")}
    )

    message: Optional["Message"] = Relationship(back_populates="attachments")


class CustomEmoji(SQLModel, table=True):
    __tablename__ = "custom_emojis"  # type: ignore

    id: str = Field(primary_key=True)
    server_id: str = Field(foreign_key="servers.id")
    name: str
    url: str
    created_at: Optional[datetime] = Field(
        default=None, sa_column_kwargs={"server_default": text("CURRENT_TIMESTAMP")}
    )
